# This workflow installs Python dependencies, runs unit tests and uploads coverage reports.
# Info: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python unit test and coverage report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [ '3.11', '3.12', '3.13' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest==8.3.3 pytest-cov==5.0.0

      - name: Run unit tests
        run: pytest test/ --cov=changelist_sort --cov-report=html --cov-fail-under=96

      - name: Upload Test Coverage Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cl-sort-cov-${{ matrix.os }}-${{ matrix.python-version }}
          path: htmlcov/
