# This workflow installs Python and test dependencies, runs unit tests and coverage reports.
# Info: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Run Faster Tests on Pull Requests into Release
on:
  pull_request:
    branches: [ release-* ]

jobs:
  build:
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.13' ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest==8.3.5 pytest-cov==6.1.1

      - name: Run unit tests
        run: pytest test/ --cov=changelist_sort --cov-report=html

      - name: Upload Test Coverage Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cl-sort-cov-${{ matrix.python-version }}
          path: htmlcov/
